backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "src/images/resize-src/beers" # Media files will be stored in the repo under images/uploads
public_folder: "dist/images/resize-src/beers"
collections:
  - name: "products" # Used in routes, e.g., /admin/collections/blog
    label: "Products" # Used in the UI
    folder: "src/data/beers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "product"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Style", name: "style", widget: "string"}
      - {label: "Url", name: "url", widget: "string"}
      - {label: "Background", name: "bg", widget: "string"}
      - {label: "ABV", name: "abv", widget: "number"}
      - {label: "OG", name: "og", widget: "number"}
      - {label: "FG", name: "fg", widget: "number"}
      - {label: "Untappd Id", name: "untappdId", widget: "number"}
      - {label: "Available", name: "available", widget: "boolean"}
      - {label: "New", name: "new", widget: "boolean"}
      - {label: "Soon", name: "soon", widget: "boolean"}
      - {label: "Featured", name: "featured", widget: "boolean"}
      - {label: "Description", name: "featured", widget: "list"}
      - {label: "Ingredients", name: "ingredients", widget: "list"}
      - {label: "Image", name: "image", widget: "image"}
